/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.passive.faros;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Data from temperature sensor expressed in degrees on the Celsius (°C) scale. */
@org.apache.avro.specific.AvroGenerated
public class FarosTemperature extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6140535290016047882L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FarosTemperature\",\"namespace\":\"org.radarcns.passive.faros\",\"doc\":\"Data from temperature sensor expressed in degrees on the Celsius (°C) scale.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"Device timestamp in UTC (s).\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"Device receiver timestamp in UTC (s).\"},{\"name\":\"temperature\",\"type\":\"float\",\"doc\":\"Skin temperature (C).\"},{\"name\":\"temperatureRaw\",\"type\":\"int\",\"doc\":\"Skin temperature expressed in ADC values.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FarosTemperature> ENCODER =
      new BinaryMessageEncoder<FarosTemperature>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FarosTemperature> DECODER =
      new BinaryMessageDecoder<FarosTemperature>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FarosTemperature> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FarosTemperature> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FarosTemperature>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FarosTemperature to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FarosTemperature from a ByteBuffer. */
  public static FarosTemperature fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device timestamp in UTC (s). */
  @Deprecated public double time;
  /** Device receiver timestamp in UTC (s). */
  @Deprecated public double timeReceived;
  /** Skin temperature (C). */
  @Deprecated public float temperature;
  /** Skin temperature expressed in ADC values. */
  @Deprecated public int temperatureRaw;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FarosTemperature() {}

  /**
   * All-args constructor.
   * @param time Device timestamp in UTC (s).
   * @param timeReceived Device receiver timestamp in UTC (s).
   * @param temperature Skin temperature (C).
   * @param temperatureRaw Skin temperature expressed in ADC values.
   */
  public FarosTemperature(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float temperature, java.lang.Integer temperatureRaw) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.temperature = temperature;
    this.temperatureRaw = temperatureRaw;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return temperature;
    case 3: return temperatureRaw;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: temperature = (java.lang.Float)value$; break;
    case 3: temperatureRaw = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return Device timestamp in UTC (s).
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * Device timestamp in UTC (s).
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return Device receiver timestamp in UTC (s).
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * Device receiver timestamp in UTC (s).
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return Skin temperature (C).
   */
  public java.lang.Float getTemperature() {
    return temperature;
  }

  /**
   * Sets the value of the 'temperature' field.
   * Skin temperature (C).
   * @param value the value to set.
   */
  public void setTemperature(java.lang.Float value) {
    this.temperature = value;
  }

  /**
   * Gets the value of the 'temperatureRaw' field.
   * @return Skin temperature expressed in ADC values.
   */
  public java.lang.Integer getTemperatureRaw() {
    return temperatureRaw;
  }

  /**
   * Sets the value of the 'temperatureRaw' field.
   * Skin temperature expressed in ADC values.
   * @param value the value to set.
   */
  public void setTemperatureRaw(java.lang.Integer value) {
    this.temperatureRaw = value;
  }

  /**
   * Creates a new FarosTemperature RecordBuilder.
   * @return A new FarosTemperature RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosTemperature.Builder newBuilder() {
    return new org.radarcns.passive.faros.FarosTemperature.Builder();
  }

  /**
   * Creates a new FarosTemperature RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FarosTemperature RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosTemperature.Builder newBuilder(org.radarcns.passive.faros.FarosTemperature.Builder other) {
    return new org.radarcns.passive.faros.FarosTemperature.Builder(other);
  }

  /**
   * Creates a new FarosTemperature RecordBuilder by copying an existing FarosTemperature instance.
   * @param other The existing instance to copy.
   * @return A new FarosTemperature RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosTemperature.Builder newBuilder(org.radarcns.passive.faros.FarosTemperature other) {
    return new org.radarcns.passive.faros.FarosTemperature.Builder(other);
  }

  /**
   * RecordBuilder for FarosTemperature instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FarosTemperature>
    implements org.apache.avro.data.RecordBuilder<FarosTemperature> {

    /** Device timestamp in UTC (s). */
    private double time;
    /** Device receiver timestamp in UTC (s). */
    private double timeReceived;
    /** Skin temperature (C). */
    private float temperature;
    /** Skin temperature expressed in ADC values. */
    private int temperatureRaw;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.passive.faros.FarosTemperature.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureRaw)) {
        this.temperatureRaw = data().deepCopy(fields()[3].schema(), other.temperatureRaw);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FarosTemperature instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.passive.faros.FarosTemperature other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureRaw)) {
        this.temperatureRaw = data().deepCopy(fields()[3].schema(), other.temperatureRaw);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * Device timestamp in UTC (s).
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * Device receiver timestamp in UTC (s).
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * Skin temperature (C).
      * @return The value.
      */
    public java.lang.Float getTemperature() {
      return temperature;
    }

    /**
      * Sets the value of the 'temperature' field.
      * Skin temperature (C).
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder setTemperature(float value) {
      validate(fields()[2], value);
      this.temperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * Skin temperature (C).
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'temperature' field.
      * Skin temperature (C).
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder clearTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatureRaw' field.
      * Skin temperature expressed in ADC values.
      * @return The value.
      */
    public java.lang.Integer getTemperatureRaw() {
      return temperatureRaw;
    }

    /**
      * Sets the value of the 'temperatureRaw' field.
      * Skin temperature expressed in ADC values.
      * @param value The value of 'temperatureRaw'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder setTemperatureRaw(int value) {
      validate(fields()[3], value);
      this.temperatureRaw = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatureRaw' field has been set.
      * Skin temperature expressed in ADC values.
      * @return True if the 'temperatureRaw' field has been set, false otherwise.
      */
    public boolean hasTemperatureRaw() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'temperatureRaw' field.
      * Skin temperature expressed in ADC values.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosTemperature.Builder clearTemperatureRaw() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FarosTemperature build() {
      try {
        FarosTemperature record = new FarosTemperature();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.temperature = fieldSetFlags()[2] ? this.temperature : (java.lang.Float) defaultValue(fields()[2]);
        record.temperatureRaw = fieldSetFlags()[3] ? this.temperatureRaw : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FarosTemperature>
    WRITER$ = (org.apache.avro.io.DatumWriter<FarosTemperature>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FarosTemperature>
    READER$ = (org.apache.avro.io.DatumReader<FarosTemperature>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
