/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.passive.faros;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Data from 1, 2 or 3 channel electrocardiography electrodes */
@org.apache.avro.specific.AvroGenerated
public class FarosEcg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3134652702681562164L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FarosEcg\",\"namespace\":\"org.radarcns.passive.faros\",\"doc\":\"Data from 1, 2 or 3 channel electrocardiography electrodes\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"Device timestamp in UTC (s).\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"Device receiver timestamp in UTC (s).\"},{\"name\":\"channel1\",\"type\":\"float\",\"doc\":\"ecg signal from the first channel (µV)\"},{\"name\":\"channel2\",\"type\":\"float\",\"doc\":\"ecg signal from the first channel (µV)\"},{\"name\":\"channel3\",\"type\":\"float\",\"doc\":\"ecg signal from the first channel (µV)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FarosEcg> ENCODER =
      new BinaryMessageEncoder<FarosEcg>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FarosEcg> DECODER =
      new BinaryMessageDecoder<FarosEcg>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FarosEcg> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FarosEcg> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FarosEcg>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FarosEcg to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FarosEcg from a ByteBuffer. */
  public static FarosEcg fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device timestamp in UTC (s). */
  @Deprecated public double time;
  /** Device receiver timestamp in UTC (s). */
  @Deprecated public double timeReceived;
  /** ecg signal from the first channel (µV) */
  @Deprecated public float channel1;
  /** ecg signal from the first channel (µV) */
  @Deprecated public float channel2;
  /** ecg signal from the first channel (µV) */
  @Deprecated public float channel3;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FarosEcg() {}

  /**
   * All-args constructor.
   * @param time Device timestamp in UTC (s).
   * @param timeReceived Device receiver timestamp in UTC (s).
   * @param channel1 ecg signal from the first channel (µV)
   * @param channel2 ecg signal from the first channel (µV)
   * @param channel3 ecg signal from the first channel (µV)
   */
  public FarosEcg(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float channel1, java.lang.Float channel2, java.lang.Float channel3) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.channel1 = channel1;
    this.channel2 = channel2;
    this.channel3 = channel3;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return channel1;
    case 3: return channel2;
    case 4: return channel3;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: channel1 = (java.lang.Float)value$; break;
    case 3: channel2 = (java.lang.Float)value$; break;
    case 4: channel3 = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return Device timestamp in UTC (s).
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * Device timestamp in UTC (s).
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return Device receiver timestamp in UTC (s).
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * Device receiver timestamp in UTC (s).
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'channel1' field.
   * @return ecg signal from the first channel (µV)
   */
  public java.lang.Float getChannel1() {
    return channel1;
  }

  /**
   * Sets the value of the 'channel1' field.
   * ecg signal from the first channel (µV)
   * @param value the value to set.
   */
  public void setChannel1(java.lang.Float value) {
    this.channel1 = value;
  }

  /**
   * Gets the value of the 'channel2' field.
   * @return ecg signal from the first channel (µV)
   */
  public java.lang.Float getChannel2() {
    return channel2;
  }

  /**
   * Sets the value of the 'channel2' field.
   * ecg signal from the first channel (µV)
   * @param value the value to set.
   */
  public void setChannel2(java.lang.Float value) {
    this.channel2 = value;
  }

  /**
   * Gets the value of the 'channel3' field.
   * @return ecg signal from the first channel (µV)
   */
  public java.lang.Float getChannel3() {
    return channel3;
  }

  /**
   * Sets the value of the 'channel3' field.
   * ecg signal from the first channel (µV)
   * @param value the value to set.
   */
  public void setChannel3(java.lang.Float value) {
    this.channel3 = value;
  }

  /**
   * Creates a new FarosEcg RecordBuilder.
   * @return A new FarosEcg RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosEcg.Builder newBuilder() {
    return new org.radarcns.passive.faros.FarosEcg.Builder();
  }

  /**
   * Creates a new FarosEcg RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FarosEcg RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosEcg.Builder newBuilder(org.radarcns.passive.faros.FarosEcg.Builder other) {
    return new org.radarcns.passive.faros.FarosEcg.Builder(other);
  }

  /**
   * Creates a new FarosEcg RecordBuilder by copying an existing FarosEcg instance.
   * @param other The existing instance to copy.
   * @return A new FarosEcg RecordBuilder
   */
  public static org.radarcns.passive.faros.FarosEcg.Builder newBuilder(org.radarcns.passive.faros.FarosEcg other) {
    return new org.radarcns.passive.faros.FarosEcg.Builder(other);
  }

  /**
   * RecordBuilder for FarosEcg instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FarosEcg>
    implements org.apache.avro.data.RecordBuilder<FarosEcg> {

    /** Device timestamp in UTC (s). */
    private double time;
    /** Device receiver timestamp in UTC (s). */
    private double timeReceived;
    /** ecg signal from the first channel (µV) */
    private float channel1;
    /** ecg signal from the first channel (µV) */
    private float channel2;
    /** ecg signal from the first channel (µV) */
    private float channel3;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.passive.faros.FarosEcg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.channel1)) {
        this.channel1 = data().deepCopy(fields()[2].schema(), other.channel1);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channel2)) {
        this.channel2 = data().deepCopy(fields()[3].schema(), other.channel2);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.channel3)) {
        this.channel3 = data().deepCopy(fields()[4].schema(), other.channel3);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FarosEcg instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.passive.faros.FarosEcg other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.channel1)) {
        this.channel1 = data().deepCopy(fields()[2].schema(), other.channel1);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channel2)) {
        this.channel2 = data().deepCopy(fields()[3].schema(), other.channel2);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.channel3)) {
        this.channel3 = data().deepCopy(fields()[4].schema(), other.channel3);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * Device timestamp in UTC (s).
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * Device receiver timestamp in UTC (s).
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * Device receiver timestamp in UTC (s).
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel1' field.
      * ecg signal from the first channel (µV)
      * @return The value.
      */
    public java.lang.Float getChannel1() {
      return channel1;
    }

    /**
      * Sets the value of the 'channel1' field.
      * ecg signal from the first channel (µV)
      * @param value The value of 'channel1'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder setChannel1(float value) {
      validate(fields()[2], value);
      this.channel1 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'channel1' field has been set.
      * ecg signal from the first channel (µV)
      * @return True if the 'channel1' field has been set, false otherwise.
      */
    public boolean hasChannel1() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'channel1' field.
      * ecg signal from the first channel (µV)
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder clearChannel1() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel2' field.
      * ecg signal from the first channel (µV)
      * @return The value.
      */
    public java.lang.Float getChannel2() {
      return channel2;
    }

    /**
      * Sets the value of the 'channel2' field.
      * ecg signal from the first channel (µV)
      * @param value The value of 'channel2'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder setChannel2(float value) {
      validate(fields()[3], value);
      this.channel2 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'channel2' field has been set.
      * ecg signal from the first channel (µV)
      * @return True if the 'channel2' field has been set, false otherwise.
      */
    public boolean hasChannel2() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'channel2' field.
      * ecg signal from the first channel (µV)
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder clearChannel2() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel3' field.
      * ecg signal from the first channel (µV)
      * @return The value.
      */
    public java.lang.Float getChannel3() {
      return channel3;
    }

    /**
      * Sets the value of the 'channel3' field.
      * ecg signal from the first channel (µV)
      * @param value The value of 'channel3'.
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder setChannel3(float value) {
      validate(fields()[4], value);
      this.channel3 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'channel3' field has been set.
      * ecg signal from the first channel (µV)
      * @return True if the 'channel3' field has been set, false otherwise.
      */
    public boolean hasChannel3() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'channel3' field.
      * ecg signal from the first channel (µV)
      * @return This builder.
      */
    public org.radarcns.passive.faros.FarosEcg.Builder clearChannel3() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FarosEcg build() {
      try {
        FarosEcg record = new FarosEcg();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.channel1 = fieldSetFlags()[2] ? this.channel1 : (java.lang.Float) defaultValue(fields()[2]);
        record.channel2 = fieldSetFlags()[3] ? this.channel2 : (java.lang.Float) defaultValue(fields()[3]);
        record.channel3 = fieldSetFlags()[4] ? this.channel3 : (java.lang.Float) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FarosEcg>
    WRITER$ = (org.apache.avro.io.DatumWriter<FarosEcg>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FarosEcg>
    READER$ = (org.apache.avro.io.DatumReader<FarosEcg>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
